apiVersion: v1
kind: ReplicationController
metadata:
  name: incatalystservices-rc
spec:
  replicas: 3
  selector:
    app: microserviceapps
  template:
    metadata:
      labels:
        app: microserviceapps
    spec:
      containers:
      - name: ic-springbootservice
        image: b.gcr.io/ic-jenkins-container/ic-springbootservice
        ports:
          - containerPort: 9090
