apiVersion: v1
kind: Service
metadata:
  name: springmicroservices-svc
spec:
  ports:  
  - port: 9090
    name: springbootservice
  selector:
    app: microserviceapps
  clusterIP: 10.99.240.110
  type: LoadBalancer